// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module computation (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        O_BRAM_0_address0,
        O_BRAM_0_ce0,
        O_BRAM_0_q0,
        O_BRAM_0_address1,
        O_BRAM_0_ce1,
        O_BRAM_0_we1,
        O_BRAM_0_d1,
        O_BRAM_1_address0,
        O_BRAM_1_ce0,
        O_BRAM_1_q0,
        O_BRAM_1_address1,
        O_BRAM_1_ce1,
        O_BRAM_1_we1,
        O_BRAM_1_d1,
        O_BRAM_2_address0,
        O_BRAM_2_ce0,
        O_BRAM_2_q0,
        O_BRAM_2_address1,
        O_BRAM_2_ce1,
        O_BRAM_2_we1,
        O_BRAM_2_d1,
        O_BRAM_3_address0,
        O_BRAM_3_ce0,
        O_BRAM_3_q0,
        O_BRAM_3_address1,
        O_BRAM_3_ce1,
        O_BRAM_3_we1,
        O_BRAM_3_d1,
        I_BRAM_0_address0,
        I_BRAM_0_ce0,
        I_BRAM_0_q0,
        I_BRAM_1_address0,
        I_BRAM_1_ce0,
        I_BRAM_1_q0,
        W_BRAM_0_0_address0,
        W_BRAM_0_0_ce0,
        W_BRAM_0_0_q0,
        W_BRAM_0_1_address0,
        W_BRAM_0_1_ce0,
        W_BRAM_0_1_q0,
        W_BRAM_1_0_address0,
        W_BRAM_1_0_ce0,
        W_BRAM_1_0_q0,
        W_BRAM_1_1_address0,
        W_BRAM_1_1_ce0,
        W_BRAM_1_1_q0,
        W_BRAM_2_0_address0,
        W_BRAM_2_0_ce0,
        W_BRAM_2_0_q0,
        W_BRAM_2_1_address0,
        W_BRAM_2_1_ce0,
        W_BRAM_2_1_q0,
        W_BRAM_3_0_address0,
        W_BRAM_3_0_ce0,
        W_BRAM_3_0_q0,
        W_BRAM_3_1_address0,
        W_BRAM_3_1_ce0,
        W_BRAM_3_1_q0
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state9 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] O_BRAM_0_address0;
output   O_BRAM_0_ce0;
input  [15:0] O_BRAM_0_q0;
output  [7:0] O_BRAM_0_address1;
output   O_BRAM_0_ce1;
output   O_BRAM_0_we1;
output  [15:0] O_BRAM_0_d1;
output  [7:0] O_BRAM_1_address0;
output   O_BRAM_1_ce0;
input  [15:0] O_BRAM_1_q0;
output  [7:0] O_BRAM_1_address1;
output   O_BRAM_1_ce1;
output   O_BRAM_1_we1;
output  [15:0] O_BRAM_1_d1;
output  [7:0] O_BRAM_2_address0;
output   O_BRAM_2_ce0;
input  [15:0] O_BRAM_2_q0;
output  [7:0] O_BRAM_2_address1;
output   O_BRAM_2_ce1;
output   O_BRAM_2_we1;
output  [15:0] O_BRAM_2_d1;
output  [7:0] O_BRAM_3_address0;
output   O_BRAM_3_ce0;
input  [15:0] O_BRAM_3_q0;
output  [7:0] O_BRAM_3_address1;
output   O_BRAM_3_ce1;
output   O_BRAM_3_we1;
output  [15:0] O_BRAM_3_d1;
output  [7:0] I_BRAM_0_address0;
output   I_BRAM_0_ce0;
input  [15:0] I_BRAM_0_q0;
output  [7:0] I_BRAM_1_address0;
output   I_BRAM_1_ce0;
input  [15:0] I_BRAM_1_q0;
output  [3:0] W_BRAM_0_0_address0;
output   W_BRAM_0_0_ce0;
input  [15:0] W_BRAM_0_0_q0;
output  [3:0] W_BRAM_0_1_address0;
output   W_BRAM_0_1_ce0;
input  [15:0] W_BRAM_0_1_q0;
output  [3:0] W_BRAM_1_0_address0;
output   W_BRAM_1_0_ce0;
input  [15:0] W_BRAM_1_0_q0;
output  [3:0] W_BRAM_1_1_address0;
output   W_BRAM_1_1_ce0;
input  [15:0] W_BRAM_1_1_q0;
output  [3:0] W_BRAM_2_0_address0;
output   W_BRAM_2_0_ce0;
input  [15:0] W_BRAM_2_0_q0;
output  [3:0] W_BRAM_2_1_address0;
output   W_BRAM_2_1_ce0;
input  [15:0] W_BRAM_2_1_q0;
output  [3:0] W_BRAM_3_0_address0;
output   W_BRAM_3_0_ce0;
input  [15:0] W_BRAM_3_0_q0;
output  [3:0] W_BRAM_3_1_address0;
output   W_BRAM_3_1_ce0;
input  [15:0] W_BRAM_3_1_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg O_BRAM_0_ce0;
reg O_BRAM_0_ce1;
reg O_BRAM_0_we1;
reg O_BRAM_1_ce0;
reg O_BRAM_1_ce1;
reg O_BRAM_1_we1;
reg O_BRAM_2_ce0;
reg O_BRAM_2_ce1;
reg O_BRAM_2_we1;
reg O_BRAM_3_ce0;
reg O_BRAM_3_ce1;
reg O_BRAM_3_we1;
reg I_BRAM_0_ce0;
reg I_BRAM_1_ce0;
reg W_BRAM_0_0_ce0;
reg W_BRAM_0_1_ce0;
reg W_BRAM_1_0_ce0;
reg W_BRAM_1_1_ce0;
reg W_BRAM_2_0_ce0;
reg W_BRAM_2_1_ce0;
reg W_BRAM_3_0_ce0;
reg W_BRAM_3_1_ce0;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [10:0] indvar_flatten3_reg_264;
reg   [9:0] indvar_flatten4_reg_275;
reg   [7:0] indvar_flatten_reg_286;
reg   [1:0] r_reg_297;
reg   [1:0] s_reg_308;
reg   [3:0] te_reg_319;
reg   [3:0] tf_reg_330;
wire   [0:0] exitcond_flatten4_fu_341_p2;
reg   [0:0] exitcond_flatten4_reg_792;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
wire    ap_block_state7_pp0_stage0_iter5;
wire    ap_block_state8_pp0_stage0_iter6;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] ap_reg_pp0_iter1_exitcond_flatten4_reg_792;
reg   [0:0] ap_reg_pp0_iter2_exitcond_flatten4_reg_792;
reg   [0:0] ap_reg_pp0_iter3_exitcond_flatten4_reg_792;
reg   [0:0] ap_reg_pp0_iter4_exitcond_flatten4_reg_792;
reg   [0:0] ap_reg_pp0_iter5_exitcond_flatten4_reg_792;
wire   [10:0] indvar_flatten_next4_fu_347_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] exitcond_flatten_fu_353_p2;
reg   [0:0] exitcond_flatten_reg_801;
wire   [0:0] not_exitcond_flatten_fu_359_p2;
reg   [0:0] not_exitcond_flatten_reg_812;
wire   [0:0] exitcond_flatten1_fu_365_p2;
reg   [0:0] exitcond_flatten1_reg_817;
wire   [0:0] exitcond_flatten_mid_fu_371_p2;
reg   [0:0] exitcond_flatten_mid_reg_822;
wire   [0:0] tmp_13_fu_377_p2;
reg   [0:0] tmp_13_reg_830;
wire   [7:0] indvar_flatten_next_fu_389_p3;
wire   [9:0] indvar_flatten_next3_fu_403_p3;
wire   [1:0] r_cast9_mid2_fu_470_p3;
reg   [1:0] r_cast9_mid2_reg_845;
reg    ap_enable_reg_pp0_iter1;
wire   [1:0] s_cast8_mid2_fu_548_p3;
reg   [1:0] s_cast8_mid2_reg_850;
wire   [4:0] tmp_3_mid2_v_v_fu_565_p3;
reg   [4:0] tmp_3_mid2_v_v_reg_856;
reg   [4:0] ap_reg_pp0_iter2_tmp_3_mid2_v_v_reg_856;
wire   [3:0] tf_mid2_fu_611_p3;
reg   [3:0] tf_mid2_reg_861;
reg   [3:0] ap_reg_pp0_iter2_tf_mid2_reg_861;
reg   [3:0] ap_reg_pp0_iter3_tf_mid2_reg_861;
reg   [3:0] ap_reg_pp0_iter4_tf_mid2_reg_861;
wire   [3:0] tmp_5_mid2_fu_625_p3;
reg   [3:0] tmp_5_mid2_reg_867;
wire   [3:0] tmp_7_mid2_fu_633_p3;
reg   [3:0] tmp_7_mid2_reg_873;
reg   [3:0] ap_reg_pp0_iter2_tmp_7_mid2_reg_873;
reg   [3:0] ap_reg_pp0_iter3_tmp_7_mid2_reg_873;
reg   [3:0] ap_reg_pp0_iter4_tmp_7_mid2_reg_873;
wire   [3:0] tf_1_fu_641_p2;
wire   [63:0] tmp_3_mid2_fu_694_p1;
reg   [63:0] tmp_3_mid2_reg_894;
reg  signed [15:0] I_BRAM_0_load_reg_902;
reg  signed [15:0] ap_reg_pp0_iter4_I_BRAM_0_load_reg_902;
reg  signed [15:0] I_BRAM_1_load_reg_910;
wire  signed [15:0] tmp_52_0_1_fu_739_p2;
reg  signed [15:0] tmp_52_0_1_reg_943;
wire  signed [15:0] tmp_52_1_1_fu_744_p2;
reg  signed [15:0] tmp_52_1_1_reg_953;
wire  signed [15:0] tmp_52_2_1_fu_749_p2;
reg  signed [15:0] tmp_52_2_1_reg_963;
wire  signed [15:0] tmp_52_3_1_fu_754_p2;
reg  signed [15:0] tmp_52_3_1_reg_973;
reg   [7:0] O_BRAM_0_addr_reg_978;
reg   [7:0] O_BRAM_1_addr_reg_984;
reg   [7:0] O_BRAM_2_addr_reg_990;
reg   [7:0] O_BRAM_3_addr_reg_996;
wire  signed [15:0] grp_fu_768_p3;
reg  signed [15:0] tmp1_reg_1002;
reg    ap_enable_reg_pp0_iter5;
wire  signed [15:0] grp_fu_774_p3;
reg  signed [15:0] tmp2_reg_1007;
wire  signed [15:0] grp_fu_780_p3;
reg  signed [15:0] tmp3_reg_1012;
wire  signed [15:0] grp_fu_786_p3;
reg  signed [15:0] tmp4_reg_1017;
wire    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_condition_pp0_exit_iter1_state3;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter6;
reg   [1:0] ap_phi_mux_r_phi_fu_301_p4;
wire    ap_block_pp0_stage0;
reg   [1:0] ap_phi_mux_s_phi_fu_312_p4;
reg   [3:0] ap_phi_mux_te_phi_fu_323_p4;
wire   [63:0] tmp_32_cast_fu_685_p1;
wire   [63:0] tmp_33_cast_fu_708_p1;
wire   [7:0] indvar_flatten_op_fu_383_p2;
wire   [9:0] indvar_flatten25_op_fu_397_p2;
wire   [3:0] p_shl_fu_419_p3;
wire   [4:0] p_shl_cast_fu_427_p1;
wire   [4:0] r_cast_fu_411_p1;
wire   [4:0] tmp_fu_431_p2;
wire   [4:0] s_cast7_fu_437_p1;
wire   [3:0] r_cast9_fu_415_p1;
wire   [1:0] r_1_fu_453_p2;
wire   [3:0] p_shl_mid1_fu_481_p3;
wire   [4:0] p_shl_cast_mid1_fu_489_p1;
wire   [4:0] r_cast_mid1_fu_466_p1;
wire   [4:0] tmp_mid1_fu_493_p2;
wire   [4:0] tmp_s_fu_441_p2;
wire   [3:0] tmp_5_mid_cast_fu_513_p1;
wire   [3:0] tmp_4_fu_447_p2;
wire   [0:0] exitcond_fu_524_p2;
wire   [1:0] s_mid_fu_459_p3;
wire   [1:0] s_1_fu_535_p2;
wire   [4:0] s_cast7_mid1_fu_555_p1;
wire   [4:0] tmp_mid2_fu_499_p3;
wire   [4:0] tmp_mid1_3_fu_559_p2;
wire   [4:0] tmp_3_mid246_v_v_fu_506_p3;
wire   [3:0] r_cast9_mid2_cast_fu_477_p1;
wire   [3:0] tmp_5_mid3_fu_517_p3;
wire   [0:0] exitcond_flatten_not_fu_579_p2;
wire   [0:0] exitcond3_mid_fu_530_p2;
wire   [0:0] not_exitcond_flatten_1_fu_584_p2;
wire   [3:0] te_mid_fu_541_p3;
wire   [0:0] exitcond3_mid1_fu_589_p2;
wire   [0:0] tmp_14_fu_601_p2;
wire   [0:0] tmp_24_fu_606_p2;
wire   [3:0] te_1_fu_595_p2;
wire   [3:0] tmp_4_mid1_fu_619_p2;
wire   [3:0] tmp_5_mid5_fu_572_p3;
wire   [7:0] tmp_25_fu_653_p3;
wire   [8:0] p_shl2_cast_fu_660_p1;
wire   [8:0] tmp_5_mid2_cast_fu_650_p1;
wire   [3:0] s_cast8_mid2_cast_fu_647_p1;
wire   [3:0] tmp_8_fu_670_p2;
wire   [8:0] tmp_15_fu_664_p2;
wire   [8:0] tmp_9_cast_fu_675_p1;
wire   [8:0] tmp_17_fu_679_p2;
wire  signed [31:0] tmp_3_mid2_v_fu_691_p1;
wire   [7:0] grp_fu_759_p3;
wire   [3:0] grp_fu_759_p0;
wire   [4:0] grp_fu_759_p1;
wire   [3:0] grp_fu_759_p2;
wire    ap_CS_fsm_state9;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [7:0] grp_fu_759_p00;
wire   [7:0] grp_fu_759_p20;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
end

HLS2x4_3_mul_mul_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
HLS2x4_3_mul_mul_bkb_U17(
    .din0(W_BRAM_0_1_q0),
    .din1(I_BRAM_1_load_reg_910),
    .dout(tmp_52_0_1_fu_739_p2)
);

HLS2x4_3_mul_mul_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
HLS2x4_3_mul_mul_bkb_U18(
    .din0(W_BRAM_1_1_q0),
    .din1(I_BRAM_1_load_reg_910),
    .dout(tmp_52_1_1_fu_744_p2)
);

HLS2x4_3_mul_mul_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
HLS2x4_3_mul_mul_bkb_U19(
    .din0(W_BRAM_2_1_q0),
    .din1(I_BRAM_1_load_reg_910),
    .dout(tmp_52_2_1_fu_749_p2)
);

HLS2x4_3_mul_mul_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
HLS2x4_3_mul_mul_bkb_U20(
    .din0(W_BRAM_3_1_q0),
    .din1(I_BRAM_1_load_reg_910),
    .dout(tmp_52_3_1_fu_754_p2)
);

HLS2x4_3_mac_mulacud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 8 ))
HLS2x4_3_mac_mulacud_U21(
    .din0(grp_fu_759_p0),
    .din1(grp_fu_759_p1),
    .din2(grp_fu_759_p2),
    .dout(grp_fu_759_p3)
);

HLS2x4_3_mac_muladEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
HLS2x4_3_mac_muladEe_U22(
    .din0(W_BRAM_0_0_q0),
    .din1(ap_reg_pp0_iter4_I_BRAM_0_load_reg_902),
    .din2(tmp_52_0_1_reg_943),
    .dout(grp_fu_768_p3)
);

HLS2x4_3_mac_muladEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
HLS2x4_3_mac_muladEe_U23(
    .din0(W_BRAM_1_0_q0),
    .din1(ap_reg_pp0_iter4_I_BRAM_0_load_reg_902),
    .din2(tmp_52_1_1_reg_953),
    .dout(grp_fu_774_p3)
);

HLS2x4_3_mac_muladEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
HLS2x4_3_mac_muladEe_U24(
    .din0(W_BRAM_2_0_q0),
    .din1(ap_reg_pp0_iter4_I_BRAM_0_load_reg_902),
    .din2(tmp_52_2_1_reg_963),
    .dout(grp_fu_780_p3)
);

HLS2x4_3_mac_muladEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
HLS2x4_3_mac_muladEe_U25(
    .din0(W_BRAM_3_0_q0),
    .din1(ap_reg_pp0_iter4_I_BRAM_0_load_reg_902),
    .din2(tmp_52_3_1_reg_973),
    .dout(grp_fu_786_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten4_fu_341_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter1_state3)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter6 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten4_fu_341_p2 == 1'd0))) begin
        indvar_flatten3_reg_264 <= indvar_flatten_next4_fu_347_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten3_reg_264 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten4_fu_341_p2 == 1'd0))) begin
        indvar_flatten4_reg_275 <= indvar_flatten_next3_fu_403_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten4_reg_275 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten4_fu_341_p2 == 1'd0))) begin
        indvar_flatten_reg_286 <= indvar_flatten_next_fu_389_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_286 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_reg_pp0_iter1_exitcond_flatten4_reg_792 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        r_reg_297 <= r_cast9_mid2_reg_845;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        r_reg_297 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_reg_pp0_iter1_exitcond_flatten4_reg_792 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        s_reg_308 <= s_cast8_mid2_reg_850;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        s_reg_308 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_reg_pp0_iter1_exitcond_flatten4_reg_792 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        te_reg_319 <= tmp_7_mid2_reg_873;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        te_reg_319 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten4_reg_792 == 1'd0))) begin
        tf_reg_330 <= tf_1_fu_641_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        tf_reg_330 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter2_exitcond_flatten4_reg_792 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        I_BRAM_0_load_reg_902 <= I_BRAM_0_q0;
        I_BRAM_1_load_reg_910 <= I_BRAM_1_q0;
        tmp_3_mid2_reg_894[31 : 0] <= tmp_3_mid2_fu_694_p1[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter4_exitcond_flatten4_reg_792 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        O_BRAM_0_addr_reg_978 <= tmp_33_cast_fu_708_p1;
        O_BRAM_1_addr_reg_984 <= tmp_33_cast_fu_708_p1;
        O_BRAM_2_addr_reg_990 <= tmp_33_cast_fu_708_p1;
        O_BRAM_3_addr_reg_996 <= tmp_33_cast_fu_708_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_reg_pp0_iter1_exitcond_flatten4_reg_792 <= exitcond_flatten4_reg_792;
        exitcond_flatten4_reg_792 <= exitcond_flatten4_fu_341_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_reg_pp0_iter2_exitcond_flatten4_reg_792 <= ap_reg_pp0_iter1_exitcond_flatten4_reg_792;
        ap_reg_pp0_iter2_tf_mid2_reg_861 <= tf_mid2_reg_861;
        ap_reg_pp0_iter2_tmp_3_mid2_v_v_reg_856 <= tmp_3_mid2_v_v_reg_856;
        ap_reg_pp0_iter2_tmp_7_mid2_reg_873 <= tmp_7_mid2_reg_873;
        ap_reg_pp0_iter3_exitcond_flatten4_reg_792 <= ap_reg_pp0_iter2_exitcond_flatten4_reg_792;
        ap_reg_pp0_iter3_tf_mid2_reg_861 <= ap_reg_pp0_iter2_tf_mid2_reg_861;
        ap_reg_pp0_iter3_tmp_7_mid2_reg_873 <= ap_reg_pp0_iter2_tmp_7_mid2_reg_873;
        ap_reg_pp0_iter4_I_BRAM_0_load_reg_902 <= I_BRAM_0_load_reg_902;
        ap_reg_pp0_iter4_exitcond_flatten4_reg_792 <= ap_reg_pp0_iter3_exitcond_flatten4_reg_792;
        ap_reg_pp0_iter4_tf_mid2_reg_861 <= ap_reg_pp0_iter3_tf_mid2_reg_861;
        ap_reg_pp0_iter4_tmp_7_mid2_reg_873 <= ap_reg_pp0_iter3_tmp_7_mid2_reg_873;
        ap_reg_pp0_iter5_exitcond_flatten4_reg_792 <= ap_reg_pp0_iter4_exitcond_flatten4_reg_792;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten4_fu_341_p2 == 1'd0))) begin
        exitcond_flatten1_reg_817 <= exitcond_flatten1_fu_365_p2;
        exitcond_flatten_mid_reg_822 <= exitcond_flatten_mid_fu_371_p2;
        exitcond_flatten_reg_801 <= exitcond_flatten_fu_353_p2;
        not_exitcond_flatten_reg_812 <= not_exitcond_flatten_fu_359_p2;
        tmp_13_reg_830 <= tmp_13_fu_377_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten4_reg_792 == 1'd0))) begin
        r_cast9_mid2_reg_845 <= r_cast9_mid2_fu_470_p3;
        s_cast8_mid2_reg_850 <= s_cast8_mid2_fu_548_p3;
        tmp_7_mid2_reg_873 <= tmp_7_mid2_fu_633_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten4_reg_792 == 1'd0))) begin
        tf_mid2_reg_861 <= tf_mid2_fu_611_p3;
        tmp_3_mid2_v_v_reg_856 <= tmp_3_mid2_v_v_fu_565_p3;
        tmp_5_mid2_reg_867 <= tmp_5_mid2_fu_625_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (ap_reg_pp0_iter4_exitcond_flatten4_reg_792 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp1_reg_1002 <= grp_fu_768_p3;
        tmp2_reg_1007 <= grp_fu_774_p3;
        tmp3_reg_1012 <= grp_fu_780_p3;
        tmp4_reg_1017 <= grp_fu_786_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter3_exitcond_flatten4_reg_792 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_52_0_1_reg_943 <= tmp_52_0_1_fu_739_p2;
        tmp_52_1_1_reg_953 <= tmp_52_1_1_fu_744_p2;
        tmp_52_2_1_reg_963 <= tmp_52_2_1_fu_749_p2;
        tmp_52_3_1_reg_973 <= tmp_52_3_1_fu_754_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        I_BRAM_0_ce0 = 1'b1;
    end else begin
        I_BRAM_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        I_BRAM_1_ce0 = 1'b1;
    end else begin
        I_BRAM_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        O_BRAM_0_ce0 = 1'b1;
    end else begin
        O_BRAM_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        O_BRAM_0_ce1 = 1'b1;
    end else begin
        O_BRAM_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (ap_reg_pp0_iter5_exitcond_flatten4_reg_792 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        O_BRAM_0_we1 = 1'b1;
    end else begin
        O_BRAM_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        O_BRAM_1_ce0 = 1'b1;
    end else begin
        O_BRAM_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        O_BRAM_1_ce1 = 1'b1;
    end else begin
        O_BRAM_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (ap_reg_pp0_iter5_exitcond_flatten4_reg_792 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        O_BRAM_1_we1 = 1'b1;
    end else begin
        O_BRAM_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        O_BRAM_2_ce0 = 1'b1;
    end else begin
        O_BRAM_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        O_BRAM_2_ce1 = 1'b1;
    end else begin
        O_BRAM_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (ap_reg_pp0_iter5_exitcond_flatten4_reg_792 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        O_BRAM_2_we1 = 1'b1;
    end else begin
        O_BRAM_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        O_BRAM_3_ce0 = 1'b1;
    end else begin
        O_BRAM_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        O_BRAM_3_ce1 = 1'b1;
    end else begin
        O_BRAM_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (ap_reg_pp0_iter5_exitcond_flatten4_reg_792 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        O_BRAM_3_we1 = 1'b1;
    end else begin
        O_BRAM_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        W_BRAM_0_0_ce0 = 1'b1;
    end else begin
        W_BRAM_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        W_BRAM_0_1_ce0 = 1'b1;
    end else begin
        W_BRAM_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        W_BRAM_1_0_ce0 = 1'b1;
    end else begin
        W_BRAM_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        W_BRAM_1_1_ce0 = 1'b1;
    end else begin
        W_BRAM_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        W_BRAM_2_0_ce0 = 1'b1;
    end else begin
        W_BRAM_2_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        W_BRAM_2_1_ce0 = 1'b1;
    end else begin
        W_BRAM_2_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        W_BRAM_3_0_ce0 = 1'b1;
    end else begin
        W_BRAM_3_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        W_BRAM_3_1_ce0 = 1'b1;
    end else begin
        W_BRAM_3_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_condition_pp0_exit_iter1_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter1_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_reg_pp0_iter1_exitcond_flatten4_reg_792 == 1'd0))) begin
        ap_phi_mux_r_phi_fu_301_p4 = r_cast9_mid2_reg_845;
    end else begin
        ap_phi_mux_r_phi_fu_301_p4 = r_reg_297;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_reg_pp0_iter1_exitcond_flatten4_reg_792 == 1'd0))) begin
        ap_phi_mux_s_phi_fu_312_p4 = s_cast8_mid2_reg_850;
    end else begin
        ap_phi_mux_s_phi_fu_312_p4 = s_reg_308;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_reg_pp0_iter1_exitcond_flatten4_reg_792 == 1'd0))) begin
        ap_phi_mux_te_phi_fu_323_p4 = tmp_7_mid2_reg_873;
    end else begin
        ap_phi_mux_te_phi_fu_323_p4 = te_reg_319;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign I_BRAM_0_address0 = tmp_32_cast_fu_685_p1;

assign I_BRAM_1_address0 = tmp_32_cast_fu_685_p1;

assign O_BRAM_0_address0 = tmp_33_cast_fu_708_p1;

assign O_BRAM_0_address1 = O_BRAM_0_addr_reg_978;

assign O_BRAM_0_d1 = ($signed(O_BRAM_0_q0) + $signed(tmp1_reg_1002));

assign O_BRAM_1_address0 = tmp_33_cast_fu_708_p1;

assign O_BRAM_1_address1 = O_BRAM_1_addr_reg_984;

assign O_BRAM_1_d1 = ($signed(O_BRAM_1_q0) + $signed(tmp2_reg_1007));

assign O_BRAM_2_address0 = tmp_33_cast_fu_708_p1;

assign O_BRAM_2_address1 = O_BRAM_2_addr_reg_990;

assign O_BRAM_2_d1 = ($signed(O_BRAM_2_q0) + $signed(tmp3_reg_1012));

assign O_BRAM_3_address0 = tmp_33_cast_fu_708_p1;

assign O_BRAM_3_address1 = O_BRAM_3_addr_reg_996;

assign O_BRAM_3_d1 = ($signed(O_BRAM_3_q0) + $signed(tmp4_reg_1017));

assign W_BRAM_0_0_address0 = tmp_3_mid2_reg_894;

assign W_BRAM_0_1_address0 = tmp_3_mid2_fu_694_p1;

assign W_BRAM_1_0_address0 = tmp_3_mid2_reg_894;

assign W_BRAM_1_1_address0 = tmp_3_mid2_fu_694_p1;

assign W_BRAM_2_0_address0 = tmp_3_mid2_reg_894;

assign W_BRAM_2_1_address0 = tmp_3_mid2_fu_694_p1;

assign W_BRAM_3_0_address0 = tmp_3_mid2_reg_894;

assign W_BRAM_3_1_address0 = tmp_3_mid2_fu_694_p1;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign exitcond3_mid1_fu_589_p2 = (not_exitcond_flatten_1_fu_584_p2 & exitcond3_mid_fu_530_p2);

assign exitcond3_mid_fu_530_p2 = (not_exitcond_flatten_reg_812 & exitcond_fu_524_p2);

assign exitcond_flatten1_fu_365_p2 = ((indvar_flatten_reg_286 == 8'd169) ? 1'b1 : 1'b0);

assign exitcond_flatten4_fu_341_p2 = ((indvar_flatten3_reg_264 == 11'd1521) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_353_p2 = ((indvar_flatten4_reg_275 == 10'd507) ? 1'b1 : 1'b0);

assign exitcond_flatten_mid_fu_371_p2 = (not_exitcond_flatten_fu_359_p2 & exitcond_flatten1_fu_365_p2);

assign exitcond_flatten_not_fu_579_p2 = (exitcond_flatten1_reg_817 ^ 1'd1);

assign exitcond_fu_524_p2 = ((tf_reg_330 == 4'd13) ? 1'b1 : 1'b0);

assign grp_fu_759_p0 = grp_fu_759_p00;

assign grp_fu_759_p00 = ap_reg_pp0_iter4_tmp_7_mid2_reg_873;

assign grp_fu_759_p1 = 8'd13;

assign grp_fu_759_p2 = grp_fu_759_p20;

assign grp_fu_759_p20 = ap_reg_pp0_iter4_tf_mid2_reg_861;

assign indvar_flatten25_op_fu_397_p2 = (indvar_flatten4_reg_275 + 10'd1);

assign indvar_flatten_next3_fu_403_p3 = ((exitcond_flatten_fu_353_p2[0:0] === 1'b1) ? 10'd1 : indvar_flatten25_op_fu_397_p2);

assign indvar_flatten_next4_fu_347_p2 = (indvar_flatten3_reg_264 + 11'd1);

assign indvar_flatten_next_fu_389_p3 = ((tmp_13_fu_377_p2[0:0] === 1'b1) ? 8'd1 : indvar_flatten_op_fu_383_p2);

assign indvar_flatten_op_fu_383_p2 = (indvar_flatten_reg_286 + 8'd1);

assign not_exitcond_flatten_1_fu_584_p2 = (exitcond_flatten_reg_801 | exitcond_flatten_not_fu_579_p2);

assign not_exitcond_flatten_fu_359_p2 = (exitcond_flatten_fu_353_p2 ^ 1'd1);

assign p_shl2_cast_fu_660_p1 = tmp_25_fu_653_p3;

assign p_shl_cast_fu_427_p1 = p_shl_fu_419_p3;

assign p_shl_cast_mid1_fu_489_p1 = p_shl_mid1_fu_481_p3;

assign p_shl_fu_419_p3 = {{ap_phi_mux_r_phi_fu_301_p4}, {2'd0}};

assign p_shl_mid1_fu_481_p3 = {{r_1_fu_453_p2}, {2'd0}};

assign r_1_fu_453_p2 = (ap_phi_mux_r_phi_fu_301_p4 + 2'd1);

assign r_cast9_fu_415_p1 = ap_phi_mux_r_phi_fu_301_p4;

assign r_cast9_mid2_cast_fu_477_p1 = r_cast9_mid2_fu_470_p3;

assign r_cast9_mid2_fu_470_p3 = ((exitcond_flatten_reg_801[0:0] === 1'b1) ? r_1_fu_453_p2 : ap_phi_mux_r_phi_fu_301_p4);

assign r_cast_fu_411_p1 = ap_phi_mux_r_phi_fu_301_p4;

assign r_cast_mid1_fu_466_p1 = r_1_fu_453_p2;

assign s_1_fu_535_p2 = (s_mid_fu_459_p3 + 2'd1);

assign s_cast7_fu_437_p1 = ap_phi_mux_s_phi_fu_312_p4;

assign s_cast7_mid1_fu_555_p1 = s_1_fu_535_p2;

assign s_cast8_mid2_cast_fu_647_p1 = s_cast8_mid2_reg_850;

assign s_cast8_mid2_fu_548_p3 = ((exitcond_flatten_mid_reg_822[0:0] === 1'b1) ? s_1_fu_535_p2 : s_mid_fu_459_p3);

assign s_mid_fu_459_p3 = ((exitcond_flatten_reg_801[0:0] === 1'b1) ? 2'd0 : ap_phi_mux_s_phi_fu_312_p4);

assign te_1_fu_595_p2 = (te_mid_fu_541_p3 + 4'd1);

assign te_mid_fu_541_p3 = ((tmp_13_reg_830[0:0] === 1'b1) ? 4'd0 : ap_phi_mux_te_phi_fu_323_p4);

assign tf_1_fu_641_p2 = (tf_mid2_fu_611_p3 + 4'd1);

assign tf_mid2_fu_611_p3 = ((tmp_24_fu_606_p2[0:0] === 1'b1) ? 4'd0 : tf_reg_330);

assign tmp_13_fu_377_p2 = (exitcond_flatten_mid_fu_371_p2 | exitcond_flatten_fu_353_p2);

assign tmp_14_fu_601_p2 = (exitcond_flatten_mid_reg_822 | exitcond3_mid1_fu_589_p2);

assign tmp_15_fu_664_p2 = (p_shl2_cast_fu_660_p1 - tmp_5_mid2_cast_fu_650_p1);

assign tmp_17_fu_679_p2 = (tmp_15_fu_664_p2 + tmp_9_cast_fu_675_p1);

assign tmp_24_fu_606_p2 = (tmp_14_fu_601_p2 | exitcond_flatten_reg_801);

assign tmp_25_fu_653_p3 = {{tmp_5_mid2_reg_867}, {4'd0}};

assign tmp_32_cast_fu_685_p1 = tmp_17_fu_679_p2;

assign tmp_33_cast_fu_708_p1 = grp_fu_759_p3;

assign tmp_3_mid246_v_v_fu_506_p3 = ((exitcond_flatten_reg_801[0:0] === 1'b1) ? tmp_mid1_fu_493_p2 : tmp_s_fu_441_p2);

assign tmp_3_mid2_fu_694_p1 = $unsigned(tmp_3_mid2_v_fu_691_p1);

assign tmp_3_mid2_v_fu_691_p1 = $signed(ap_reg_pp0_iter2_tmp_3_mid2_v_v_reg_856);

assign tmp_3_mid2_v_v_fu_565_p3 = ((exitcond_flatten_mid_reg_822[0:0] === 1'b1) ? tmp_mid1_3_fu_559_p2 : tmp_3_mid246_v_v_fu_506_p3);

assign tmp_4_fu_447_p2 = (r_cast9_fu_415_p1 + ap_phi_mux_te_phi_fu_323_p4);

assign tmp_4_mid1_fu_619_p2 = (te_1_fu_595_p2 + r_cast9_mid2_cast_fu_477_p1);

assign tmp_5_mid2_cast_fu_650_p1 = tmp_5_mid2_reg_867;

assign tmp_5_mid2_fu_625_p3 = ((exitcond3_mid1_fu_589_p2[0:0] === 1'b1) ? tmp_4_mid1_fu_619_p2 : tmp_5_mid5_fu_572_p3);

assign tmp_5_mid3_fu_517_p3 = ((exitcond_flatten_reg_801[0:0] === 1'b1) ? tmp_5_mid_cast_fu_513_p1 : tmp_4_fu_447_p2);

assign tmp_5_mid5_fu_572_p3 = ((exitcond_flatten_mid_reg_822[0:0] === 1'b1) ? r_cast9_mid2_cast_fu_477_p1 : tmp_5_mid3_fu_517_p3);

assign tmp_5_mid_cast_fu_513_p1 = r_1_fu_453_p2;

assign tmp_7_mid2_fu_633_p3 = ((exitcond3_mid1_fu_589_p2[0:0] === 1'b1) ? te_1_fu_595_p2 : te_mid_fu_541_p3);

assign tmp_8_fu_670_p2 = (tf_mid2_reg_861 + s_cast8_mid2_cast_fu_647_p1);

assign tmp_9_cast_fu_675_p1 = tmp_8_fu_670_p2;

assign tmp_fu_431_p2 = (p_shl_cast_fu_427_p1 - r_cast_fu_411_p1);

assign tmp_mid1_3_fu_559_p2 = (s_cast7_mid1_fu_555_p1 + tmp_mid2_fu_499_p3);

assign tmp_mid1_fu_493_p2 = (p_shl_cast_mid1_fu_489_p1 - r_cast_mid1_fu_466_p1);

assign tmp_mid2_fu_499_p3 = ((exitcond_flatten_reg_801[0:0] === 1'b1) ? tmp_mid1_fu_493_p2 : tmp_fu_431_p2);

assign tmp_s_fu_441_p2 = (tmp_fu_431_p2 + s_cast7_fu_437_p1);

always @ (posedge ap_clk) begin
    tmp_3_mid2_reg_894[63:32] <= 32'b00000000000000000000000000000000;
end

endmodule //computation
