# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_HLS2x4_2_0_0/design_1_HLS2x4_2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_HLS2x4_2_0_0 || ORIG_REF_NAME==design_1_HLS2x4_2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_1/design_1_axi_dma_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_1 || ORIG_REF_NAME==design_1_axi_dma_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_2_2/design_1_axi_dma_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dma_2_2 || ORIG_REF_NAME==design_1_axi_dma_2_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_0/design_1_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_1/design_1_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_1 || ORIG_REF_NAME==design_1_xbar_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_3_0/design_1_axi_dma_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dma_3_0 || ORIG_REF_NAME==design_1_axi_dma_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_4_0/design_1_axi_dma_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dma_4_0 || ORIG_REF_NAME==design_1_axi_dma_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_5_0/design_1_axi_dma_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dma_5_0 || ORIG_REF_NAME==design_1_axi_dma_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_HLS2x4_3_0_0/design_1_HLS2x4_3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_HLS2x4_3_0_0 || ORIG_REF_NAME==design_1_HLS2x4_3_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_6_0/design_1_axi_dma_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dma_6_0 || ORIG_REF_NAME==design_1_axi_dma_6_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_7_0/design_1_axi_dma_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dma_7_0 || ORIG_REF_NAME==design_1_axi_dma_7_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_8_0/design_1_axi_dma_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dma_8_0 || ORIG_REF_NAME==design_1_axi_dma_8_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_HLS2x4_4_0_0/design_1_HLS2x4_4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_HLS2x4_4_0_0 || ORIG_REF_NAME==design_1_HLS2x4_4_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_HLS2x4_5_0_0/design_1_HLS2x4_5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_HLS2x4_5_0_0 || ORIG_REF_NAME==design_1_HLS2x4_5_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_9_0/design_1_axi_dma_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dma_9_0 || ORIG_REF_NAME==design_1_axi_dma_9_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_10_0/design_1_axi_dma_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dma_10_0 || ORIG_REF_NAME==design_1_axi_dma_10_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_11_0/design_1_axi_dma_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dma_11_0 || ORIG_REF_NAME==design_1_axi_dma_11_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_11/design_1_auto_us_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_11 || ORIG_REF_NAME==design_1_auto_us_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_10/design_1_auto_us_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_10 || ORIG_REF_NAME==design_1_auto_us_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_9/design_1_auto_us_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_9 || ORIG_REF_NAME==design_1_auto_us_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_8/design_1_auto_us_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_8 || ORIG_REF_NAME==design_1_auto_us_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_7/design_1_auto_us_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_7 || ORIG_REF_NAME==design_1_auto_us_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_6/design_1_auto_us_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_6 || ORIG_REF_NAME==design_1_auto_us_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_5/design_1_auto_us_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_5 || ORIG_REF_NAME==design_1_auto_us_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_4/design_1_auto_us_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_4 || ORIG_REF_NAME==design_1_auto_us_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_3/design_1_auto_us_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_3 || ORIG_REF_NAME==design_1_auto_us_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_2 || ORIG_REF_NAME==design_1_auto_us_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_1 || ORIG_REF_NAME==design_1_auto_us_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_0 || ORIG_REF_NAME==design_1_auto_us_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
