webtalk_init -webtalk_dir C:/Users/MSI/Desktop/School/2019_winter/Embedded Computing/lab2_64pointFFT/lab2_64pointFFT.sim/sim_1/behav/xsim/xsim.dir/tb_Top_FFT_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Nov 22 17:02:50 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018833" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e0f89a65-93d8-419a-9dfc-f67818096d9c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "690464f314e7453ca99b94ae7bbed345" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3505 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.19_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8048_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3772856917 -regid "" -xml C:/Users/MSI/Desktop/School/2019_winter/Embedded Computing/lab2_64pointFFT/lab2_64pointFFT.sim/sim_1/behav/xsim/xsim.dir/tb_Top_FFT_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/MSI/Desktop/School/2019_winter/Embedded Computing/lab2_64pointFFT/lab2_64pointFFT.sim/sim_1/behav/xsim/xsim.dir/tb_Top_FFT_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/MSI/Desktop/School/2019_winter/Embedded Computing/lab2_64pointFFT/lab2_64pointFFT.sim/sim_1/behav/xsim/xsim.dir/tb_Top_FFT_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
